[tools]
bat = "latest"
btop = "latest"
codex = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
git-lfs = "latest"
github-cli = "latest"
"github:jorgerojas26/lazysql" = "latest"
go = "latest"
golangci-lint = "latest"
java = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
make = "latest"
node = "latest"
pandoc = "latest"
"pipx:pgcli" = "latest"
prettier = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tlrc = "latest"
tmux = "latest"
uv = "latest"
watchexec = "latest"
yazi = "latest"
