[tools]
btop = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
go = "latest"
golangci-lint = "latest"
java = "latest"
make = "latest"
node = "latest"
prettier = "latest"
python = "latest"
rust = "latest"
tlrc = "latest"
tmux = "latest"
uv = "latest"
