[tools]
btop = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
go = "latest"
golangci-lint = "latest"
java = "latest"
jq = "latest"
make = "latest"
node = "latest"
pandoc = "latest"
postgres = "latest"
prettier = "latest"
python = "latest"
rust = "latest"
starship = "latest"
tlrc = "latest"
tmux = "latest"
uv = "latest"
watchexec = "latest"
yazi = "latest"
