"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
@\
$hostname\
:\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[username]
show_always = true
format = "[$user]($style)" # Removed default "with "

[hostname]
ssh_only = false
format = "[$hostname]($style)" # Removed default "at "

[directory]
style = "blue"
format = "[$path]($style) " # Removed default "in "
truncate_to_repo=false
truncation_length=0

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
# style = "bright-black"
#
# [git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
# style = "cyan"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"
#
# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "purple"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
# style = "bright-black"
detect_extensions = []
detect_files = []
